[[ISSUERS]]
address = "rDzDFNxV1SmhdRFJUGu7HBZHN57j8Cx3n9"
name = "Bullish"

[[TOKENS]]
issuer = "rDzDFNxV1SmhdRFJUGu7HBZHN57j8Cx3n9"
currency = "Bullish"
name = "Bullish"
desc = "Bullish on XRP (Bullish) is a digital currency on the XRPL."
icon = "https://bullishxrp.github.io/icons/bullish.png"

[[TOKENS.WEBLINKS]]
url = "https://bullishonxrp.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com/BullishTokenxrp"
type = "socialmedia"

